include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/generated/**
    - "*.g.dart"
  language:
    strict-raw-types: true
    strict-casts: false
    strict-inference: true
  plugins:
    - custom_lint

linter:
  rules:
    - prefer_relative_imports

custom_lint:
  debug: false
  rules:
    - mio_header:
      file: ./header.txt
      templates:
        author: [.*, Rapougnac]
