include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/generated/**
    - "*.g.dart"
  language:
    strict-raw-types: true
    strict-casts: false
    strict-inference: true

linter:
  rules:
    - prefer_relative_imports
