FROM node:20-alpine AS kiwii_api

# Copy code
COPY ./api /api/
WORKDIR /api

COPY ./api/package.json /api/

RUN npm i -g npm@latest

# Install deps
RUN apk add --no-cache build-base cairo-dev pango-dev jpeg-dev giflib-dev librsvg-dev

# Install dependencies
RUN npm i

RUN npm run build

CMD [ "node", "dist/index.js" ]
