version: "3.9"

services:
  kiwii:
    build:
      context: .
      dockerfile: Dockerfile
      target: kiwii
    restart: always
    env_file: .env
    container_name: kiwii

    links: [database]
    depends_on: [database]
  database:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: database
    ports:
      - '5431:5432'
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    links:
      - kiwii
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "0.0.0.0:9787:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    links:
      - prometheus
    depends_on:
      - prometheus

volumes:
  db:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
