version: '3.9'

services:
  kiwii:
    image: ghcr.io/kiwiibot/kiwii:latest
    restart: always
    env_file: .env
    container_name: kiwii
    links:
      - database
    depends_on:
      - database
    ports:
      - '8080:8080'
  database:
    image: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file: .env

volumes:
  data:
    driver: local