global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kiwii'
    scrape_interval: 5s
    static_configs:
      - targets: ['kiwii:4242']
    metrics_path: /analytics
