name: kiwii
description: A Discord bot written with nyxx and nyxx_commands.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  nyxx_commands:
    git:
      url: https://github.com/Rapougnac/nyxx_commands.git
      ref: dev
    # path: ../../../code/nyxx_commands
  postgres: ^2.6.3
  get_it: ^7.2.0
  dartx: ^1.2.0
  uwurandom: ^1.0.0
  slang: ^3.30.2
  path: ^1.8.3
  drift: ^2.13.0
  drift_postgres: ^0.1.0
  json_annotation: ^4.8.1
  http: ^1.1.0
  nyxx_extensions: ^4.1.0
  dart_openai: 4.1.2
  darq: ^2.0.0
  stdlibc: ^0.1.4
  sentry: ^7.18.0
  dart_eval: ^0.6.0
  nyxx: ^6.2.1
  overfast_api:
    # path: ../overfast_api
    git:
      url: https://git.rapougnac.moe/Rapougnac/overfast_api.git
  perspective_api:
    # path: ../perspective_api
    git:
      url: https://git.rapougnac.moe/Rapougnac/perspective_api.git

  dotenv: any
  duration: ^3.0.13
  sqlite3: ^2.4.2
  universal_html: ^2.2.4
  string_similarity: ^2.0.0
  style_cron_job: ^1.0.4+2
  neat_cache: ^2.0.4
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_helmet: ^2.3.0
dependency_overrides:
  postgres:
    git:
      url: https://github.com/isoos/postgresql-dart.git
  drift_postgres:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/drift_postgres
      ref: develop
  nyxx:
    git:
      url: https://github.com/Rapougnac/nyxx.git
      ref: feat/priv-utils
    # path: ../nyxx
  nyxx_extensions:
    git:
      url: https://github.com/nyxx-discord/nyxx_extensions.git
      ref: dev

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.13.1
  json_serializable: ^6.7.1
  lints: ^3.0.0
  shelf_router_generator: ^1.1.0
